# Retry in begin/rescue block

Begin/rescue block support `retry`. [Link to interesting post](https://blog.appsignal.com/2018/06/05/redo-retry-next.html)

```ruby
i = 0
begin
  p "run xxx func"
  xxx(ooo)
rescue => e
  i += 1
  p "err: #{e.message}"
  sleep 1
  retry if i < 3
end
# "run xxx func"
# "err: undefined local variable or method `ooo' for main:Object"
# "run xxx func"
# "err: undefined local variable or method `ooo' for main:Object"
# "run xxx func"
# "err: undefined local variable or method `ooo' for main:Object"

i
# => 3
```
